---

locus: "chr1:1-200000"
number_simulation: 50
# for single event - very recent inversion (50kya)
model_manifest: "inputFiles/model_manifest.VeryRecent.singleINV.tbl"

# for recurrent events - young inversions (250kya, 150kya, 50kya)
#model_manifest: "inputFiles/model_manifest.young.tbl"

HumanRef: inputFiles/temp.fa

seq2beRM: "CMP_CMP_1"
OutGroup: "CMP_CMP_0"

